<?xml version="1.0"?>
<robot name="i3e-d3" xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <!--xacro:arg name="robot_namespace" default="/"/-->
    <xacro:arg name="use_open_manipulator" default="false"/>

    <xacro:property name="PI" value="3.14159"/>
    
    <!-- Included URDF/XACRO Files -->
    <xacro:include filename="$(find i3e-d3_description)/urdf/materials.urdf.xacro"/>
    <xacro:include filename="$(find i3e-d3_description)/urdf/wheel.urdf.xacro"/>
    <xacro:include filename="$(find i3e-d3_description)/urdf/caster.urdf.xacro"/>
    <xacro:include filename="$(find i3e-d3_description)/urdf/accessories.urdf.xacro"/>
    <xacro:include filename="$(find i3e-d3_description)/urdf/head.urdf.xacro"/>
    <xacro:include filename="$(find i3e-d3_description)/urdf/arm.urdf.xacro"/>
    
    <!-- Base, head and neck sizes -->
    <xacro:property name="base_radius" value="0.155"/>
    <xacro:property name="base_height" value="0.34568"/>
    
    <xacro:property name="base_weight" value="0.515"/>   

    <!-- Wheel Dimensions -->
    <xacro:property name="wheel_length" value="0.0762"/>
    <xacro:property name="wheel_radius" value="0.088"/>
    <!-- Wheel Mounting Positions -->
    <xacro:property name="wheel_x_offset" value="0"/>
    <xacro:property name="wheel_y_offset" value="${wheel_length/2 + base_radius + 0.005}"/>
    <xacro:property name="wheel_z_offset" value="0.0312"/>

    <!-- Base link is the center of the robot -->
    <link name="base_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://i3e-d3_description/meshes/base_link.dae"/>
            </geometry>
        </visual>
        <collision> 
            <origin xyz="0.0 0.0 ${base_height/2 - 0.0007}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_height}"/>
            </geometry>
        </collision>
    </link>

    <!-- Base footprint link is on the ground under the robot-->
    <link name="base_footprint"/>
    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0.0 0.0 ${wheel_z_offset - wheel_radius}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="base_footprint"/>
    </joint>
    
    <!-- Base inertial link -->
    <link name="inertial_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            <mass value="3"/>
            <inertia
              ixx="2.15524e-2" ixy="0.0" ixz="5.5686e-4"
              iyy="3.76598e-2" iyz="0.0"
              izz="5.25852e-2"/>
        </inertial> 
    </link>

    <joint name="inertial_joint" type="fixed">
        <parent link="base_link"/>
        <child link="inertial_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    
    <!-- I3E-D3 arms, forearms and hands -->
    <xacro:i3e-d3_arm prefix="left">
        <origin xyz="0.0 0.100 0.294" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_arm>
    <xacro:i3e-d3_arm prefix="right">
        <origin xyz="0.0 -0.100 0.294" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_arm>

    <!-- I3E-D3 head and neck -->
    <xacro:i3e-d3_head>
        <origin xyz="-0.01 0.0 ${base_height - 0.0014}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_head>

    <!-- I3E-D3 wheel macros -->
    <xacro:i3e-d3_wheel prefix="left">
        <origin xyz="${wheel_x_offset} ${wheel_y_offset} ${wheel_z_offset}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_wheel>
    <xacro:i3e-d3_wheel prefix="right">
        <origin xyz="${wheel_x_offset} ${-wheel_y_offset} ${wheel_z_offset}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_wheel>
    
    <!-- I3E-D3 caster macros -->
    <xacro:i3e-d3_caster prefix="front_caster" 
						 radius="0.025" 
						 x="${2*base_radius/3}" 
						 y="0.0" 
						 z="-0.01" 
						 roll="0.0"
						 pitch="0.0" 
						 yaw="0.0" 
						 axis_x="0.577350269" 
						 axis_y="0.577350269" 
						 axis_z="0.577350269" 
						 parent_link="base_link" />

    <xacro:i3e-d3_caster prefix="rear_caster" 
						 radius="0.025" 
						 x="${-2*base_radius/3}" 
						 y="0.0" 
						 z="-0.01" 
						 roll="0.0" 
						 pitch="0.0" 
						 yaw="0.0" 
						 axis_x="0.577350269" 
						 axis_y="0.577350269" 
						 axis_z="0.577350269" 
						 parent_link="base_link" />	
    
    <!-- Sensors -->
    <xacro:i3e-d3_camera>
      <origin xyz="0.026 0.004 0.05" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_camera>
    <xacro:i3e-d3_lidar>
        <origin xyz="${base_radius/2 - 0.012} 0.0 ${base_height - 0.0014 + 0.036 + 0.024 - 0.01}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_lidar>
    <xacro:i3e-d3_imu>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_imu>


  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <!--robotNamespace>$(arg robot_namespace)</robotNamespace-->
      <controlPeriod>0.002</controlPeriod>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
      <legacyModeNS>true</legacyModeNS>
    </plugin>
  </gazebo>    
  
</robot>
