<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="i3e-d3_wheel">
    <xacro:property name="husky_wheel_length" value="0.1143" />
    <xacro:property name="husky_wheel_radius" value="0.1651" />

    <xacro:macro name="i3e-d3_wheel" params="prefix *joint_pose">
        <link name="${prefix}_wheel_link">
            <inertial>
                <!-- Need to adjust inertia matrix -->
                <origin xyz="0.0 0.0 0.0"/>
                <mass value="1.1"/>
                <inertia
                  ixx="2.70474e-4" ixy="0.0" ixz="0.0"
                  iyy="4.38099e-4" iyz="0.0"
                  izz="2.70474e-4"/>
            </inertial>
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="package://i3e-d3_description/meshes/wheel_husky.dae"
                          scale="${wheel_radius/husky_wheel_radius} ${wheel_length/husky_wheel_length} ${wheel_radius/husky_wheel_radius}"/>
                </geometry>
                <material name="dark_gray"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${PI/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
            </collision>
        </link>

        <!-- Need to adjust gazebo properties -->
        <gazebo reference="${prefix}_wheel_link">
            <mu1 value="2.0"/>
            <mu2 value="2.0"/>
            <kp value="10000000.0" />
            <kd value="1" />
            <fdir1 value="1 0 0"/>
        </gazebo>

        <joint name="${prefix}_wheel" type="continuous">
            <xacro:insert_block name="joint_pose"/>
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="0 1 0" rpy="0.0 0.0 0.0"/>
        </joint>

        <transmission name="${prefix}_wheel_trans" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${prefix}_wheel_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${prefix}_wheel">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>

    </xacro:macro>

</robot>
